"""Generate geometry-only tables for the TDP v2 supplementary manuscript.

Only the sealed holdout manifest is read.  No TOMO or slicer outcome is touched.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "experiments" / "tdp_v2" / "manifests" / "holdout_manifest.json"
OUTPUT = ROOT / "draft" / "generated" / "tdp_v2_holdout_manifest_table.tex"


STRATUM_LABELS = {
    "faces_1k_10k": "1k--10k",
    "faces_10k_50k": "10k--50k",
    "faces_50k_150k": "50k--150k",
    "faces_150k_250k": "150k--250k",
}


def format_integer(value: int) -> str:
    return f"{int(value):,}".replace(",", "{,}")


def main() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    rows = list(manifest["meshes"])
    if len(rows) != 60:
        raise RuntimeError(f"expected 60 sealed meshes, found {len(rows)}")
    if sum(bool(row["cross_slicer"]) for row in rows) != 30:
        raise RuntimeError("expected 30 cross-slicer meshes")

    lines = [
        "% Generated by scripts/generate_tdp_v2_supplement_tables.py.",
        "% Geometry-only data: no TOMO or slicer outcomes are present.",
        r"\setlength{\LTleft}{0pt}",
        r"\setlength{\LTright}{0pt}",
        r"\stepcounter{table}",
        r"\begin{center}\textbf{\tablename\ \thetable}\ Hash-locked 60-mesh external manifest.\end{center}",
        r"\addtocounter{table}{-1}% longtable increments the counter on entry",
        r"\scriptsize",
        r"\begin{longtable}{@{}llcrrrc@{}}",
        r"\toprule",
        r"Holdout & Thingi ID & Face stratum & Faces & Vertices & $D$ & Cura/Prusa\\",
        r" & & & & & (mesh units) & panel\\",
        r"\midrule",
        r"\endfirsthead",
        r"\multicolumn{7}{c}{\tablename\ \thetable\ (continued)}\\",
        r"\toprule",
        r"Holdout & Thingi ID & Face stratum & Faces & Vertices & $D$ & Cura/Prusa\\",
        r" & & & & & (mesh units) & panel\\",
        r"\midrule",
        r"\endhead",
        r"\midrule",
        r"\multicolumn{7}{r}{Continued on next page}\\",
        r"\endfoot",
        r"\bottomrule",
        r"\endlastfoot",
    ]
    for row in rows:
        panel = "Yes" if bool(row["cross_slicer"]) else "No"
        lines.append(
            "{} & {} & {} & {} & {} & {:.3f} & {}\\\\".format(
                row["holdout_id"],
                row["thingi_id"],
                STRATUM_LABELS[row["stratum"]],
                format_integer(row["face_count"]),
                format_integer(row["vertex_count"]),
                float(row["bbox_diagonal"]),
                panel,
            )
        )
    lines.extend(
        [
            r"\end{longtable}",
            r"\normalsize",
            "",
        ]
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
